const products = [
  {
    id: 1,
    name: "Smartphone",
    description: "Latest model with advanced features",
    price: 699.99,
    category: "Electronics",
    image: "https://via.placeholder.com/150",
    stock: 20,
    rating: 4.5,
  },
  {
    id: 2,
    name: "Laptop",
    description: "High-performance laptop for work and play",
    price: 1299.99,
    category: "Electronics",
    image: "https://via.placeholder.com/150",
    stock: 15,
    rating: 4.7,
  },
  {
    id: 3,
    name: "Running Shoes",
    description: "Comfortable and durable running shoes",
    price: 89.99,
    category: "Footwear",
    image: "https://via.placeholder.com/150",
    stock: 50,
    rating: 4.2,
  },
  {
    id: 4,
    name: "Wristwatch",
    description: "Elegant wristwatch with leather strap",
    price: 199.99,
    category: "Accessories",
    image: "https://via.placeholder.com/150",
    stock: 30,
    rating: 4.0,
  },
  {
    id: 5,
    name: "Gaming Console",
    description: "Next-gen gaming console with stunning graphics",
    price: 499.99,
    category: "Electronics",
    image: "https://via.placeholder.com/150",
    stock: 10,
    rating: 4.8,
  },
];

export default products;
